# This has been created by @lillieH1000

name: Build the YouTube Reborn deb

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@main

      - name: Checkout RootHide/theos
        uses: actions/checkout@main
        with:
          repository: RootHide/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout chrisharper22/sdks
        uses: actions/checkout@main
        with:
          repository: chrisharper22/sdks
          ref: main
          sparse-checkout: iPhoneOS16.2.sdk
          path: theos/sdks

      - name: Checkout PoomSmart/YouTubeHeader
        uses: actions/checkout@main
        with:
          repository: PoomSmart/YouTubeHeader
          ref: main
          path: YouTubeHeader

      - name: Build Package 
        run: |
          brew install make ldid 
          export THEOS=theos
          gmake clean package FINALPACKAGE=1
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: packages/*.deb
